/* 
 * Sign up for a key at this location: 
 * http://code.google.com/apis/maps/signup.html
 * place the in this file
 * the forcekey should specify *.force.com as the domain for any visualforce pages
 * the key should specify *.salesforce.com for geocode requests that start on the server
 */

public class geoApiKey {
	// *.salesforce.com 
    public static string key = '';
    
    // *.force.com
    public static string forcekey = '';
 
}